### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by krissedout** [psibean/discord.js-pagination#6]
Is it possible to make an automatic pagination, it basically just gets all of the items from an array and makes an embed for every 5 items, and then puts that into the pagination pages? Is this possible, and if it is how would i do this, im fairly new to this kind of stuff..

**Comment by psibean** [comment]
I'm guessing you closed it because you figured it out?

You can construct the pages by ANY means! Supply all the embeds and the pagination will do the rest.

The next update will allow you to provide a function, which returns an embed based on the page identifiers, allowing for creating them as they are navigated, rather than having them all up front.

But you can still supply them all up front too!
